### ISSUE TITLE
[Android] Buggy animation when moving TextInput

### ISSUE THREAD

**Issue by phamhoaivu911** [IjzerenHein/react-navigation-shared-element#62] opened 2020-04-15 05:04 UTC
# Description
I have this issue when trying to transitioning the TextInput. As you can see in the gif below, there's a glitch when going back from the Search screen to the Home screen because the Keyboard is not completely closed and it affects the animation.

A possible workaround is to hide the keyboard and wait a small amount of time before going back.

I have created a PR #61 to reproduce the issue. Please take a look and let me know if there's anything I can help with. Thank you!

# Screenshots
![android_text_input_issue](https://user-images.githubusercontent.com/4929170/79300168-24b0eb00-7f10-11ea-9756-1f7ce4e0eb76.gif)|
:-:|

**Comment by IjzerenHein** [comment] 2020-04-19 14:07
Hi! Thanks for the PR and test-case 🙏 👍
Unfortunately I'm unable to reproduce the problem 🤔 See below.
Which Android device are you testing with and which version of `react-native-shared-element` are you using?

![textinput](https://user-images.githubusercontent.com/6184593/79689857-c198be80-8257-11ea-8e5c-53696209d62f.gif)

**Comment by phamhoaivu911** [comment] 2020-04-20 04:25
Hi, I'm using HUAWEI Y7 Pro 2019 device and have this issue on both real device and emulator. This is the emulator details. The above gif is from PR #61 .

```
Name: Pixel_XL_API_28

CPU/ABI: Google APIs Intel Atom (x86)

Target: google_apis [Google APIs] (API level 28)

Skin: pixel_xl_silver

SD Card: 512M

fastboot.chosenSnapshotFile: 

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: pixel_xl

hw.lcd.width: 1440

hw.initialOrientation: Portrait

image.androidVersion.api: 28

tag.id: google_apis

hw.mainKeys: no

hw.camera.front: emulated

avd.ini.displayname: Pixel XL API 28

hw.gpu.mode: auto

hw.ramSize: 1536

PlayStore.enabled: false

fastboot.forceColdBoot: no

hw.cpu.ncore: 4

hw.keyboard: yes

hw.sensors.proximity: yes

hw.dPad: no

hw.lcd.height: 2560

vm.heapSize: 384

skin.dynamic: yes

hw.device.manufacturer: Google

hw.gps: yes

hw.audioInput: yes

image.sysdir.1: system-images/android-28/google_apis/x86/

showDeviceFrame: yes

hw.camera.back: virtualscene

AvdId: Pixel_XL_API_28

hw.lcd.density: 560

hw.arc: false

hw.device.hash2: MD5:f78477654d5471c3d7f705251d14e72f

fastboot.forceChosenSnapshotBoot: no

fastboot.forceFastBoot: yes

hw.trackBall: no

hw.battery: yes

hw.sdCard: yes

tag.display: Google APIs

runtime.network.latency: none

disk.dataPartition.size: 800M

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes
```

**Comment by phamhoaivu911** [comment] 2020-04-20 04:29
This is the gif of version 5.0.0-alpha1 with react-navigation v5 on the same emulator

![Apr-20-2020 11-26-48](https://user-images.githubusercontent.com/4929170/79714111-083ef500-82fa-11ea-8337-546f3b289760.gif)|
:-:|

**Comment by german970814** [comment] 2020-09-12 01:36
Any workaround about this?

**Comment by IjzerenHein** [comment] 2021-08-19 10:25
This issue no longer occurs with the [latest official version](https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v3.1.2) and after upgrading the [latest native extensions](https://github.com/IjzerenHein/react-native-shared-element/releases).
Closing this issue thereof. Feel free to reopen with a PR for the `example` app if this problem still occurs 👍

**Comment by IjzerenHein** [comment] 2021-08-19 10:25
Android recording from the `example` app:

![textinput_android](https://user-images.githubusercontent.com/6184593/130053274-f47e3709-4773-4d2d-88d4-0bc4bea8c400.gif)

**Closed by IjzerenHein** 2021-08-19 10:25 UTC
Labels: needs repro, android
