### ISSUE TITLE
[v5] "Please specify at least one route when configuring a navigator"

### ISSUE THREAD

**Issue by chrisd1997** [IjzerenHein/react-navigation-shared-element#85] opened 2020-06-14 07:52 UTC
I'm trying to implement the v5 navigator into my project, but I'm getting the following error:

![image](https://user-images.githubusercontent.com/22114174/84588033-579a3100-ae24-11ea-89c4-7202aa47274d.png)

My code:
```
const Stack = createStackNavigator();
const Tab = createBottomTabNavigator();
const SharedStack = createSharedElementStackNavigator();

const MainGroup = () => {
    return (
        <SharedStack.Navigator initialRouteName="Onboarding" screenOptions={{headerShown: false}}>
            <SharedStack.Screen name="Onboarding" component={OnBoardingTabs} />
            <SharedStack.Screen name="Home" component={MainTab} />
        </SharedStack.Navigator>
    );
};

const App: () => React$Node = () => {
    return (
      <NavigationContainer>
          <Stack.Navigator mode="modal" screenOptions={{headerShown: false}}>
              <Stack.Screen name="Main" component={MainGroup} />
          </Stack.Navigator>
      </NavigationContainer>
    );
};
```

Am I missing a step?

**Comment by Zurdge** [comment] 2020-06-14 17:50
You're no alone. I've just come along this error too.
I'm implementing typescript into my project so it might be an issue on my side. 🤷

**Comment by chrisd1997** [comment] 2020-06-14 18:58
@Zurdge Weird.. I'm not using TypeScript though, but could be related.

**Comment by Zurdge** [comment] 2020-06-15 07:59
Really strange. 
I was able to get a clean project working this morning however I couldn't re-create the issue 😕 
These are my dependencies.
```
"dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.5.2",
    "@react-navigation/drawer": "^5.8.2",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/stack": "^5.4.2",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-maps": "0.27.1",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^3.0.2",
    "react-native-screens": "^2.8.0",
    "react-native-shared-element": "^0.7.0",
    "react-native-svg": "^12.1.0",
    "react-navigation": "^4.3.9",
    "react-navigation-shared-element": "^3.0.0",
    "react-navigation-stack": "^2.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^1.0.0",
    "@types/jest": "^24.0.24",
    "@types/react-native": "^0.62.0",
    "@types/react-test-renderer": "16.9.2",
    "@typescript-eslint/eslint-plugin": "^2.27.0",
    "@typescript-eslint/parser": "^2.27.0",
    "babel-jest": "^24.9.0",
    "babel-plugin-module-resolver": "^4.0.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "prettier": "^2.0.4",
    "react-test-renderer": "16.11.0",
    "typescript": "^3.8.3"
  },
```
Would be good to find out the cause though.

**Comment by leandrosouzaa** [comment] 2020-06-20 18:26
Same problem here. i am using TS.

my package.json

```
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/stack": "^5.5.1",
    "axios": "^0.19.2",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^3.0.5",
    "react-native-screens": "^2.9.0",
    "react-native-shared-element": "^0.7.0",
    "react-navigation": "^4.3.9",
    "react-navigation-shared-element": "^2.3.1",
    "react-navigation-stack": "^2.7.0",
    "styled-components": "^5.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^1.0.0",
    "@types/jest": "^24.0.24",
    "@types/react-native": "^0.62.0",
    "@types/react-test-renderer": "16.9.2",
    "@types/styled-components": "^5.1.0",
    "@typescript-eslint/eslint-plugin": "^3.3.0",
    "@typescript-eslint/parser": "^3.3.0",
    "babel-jest": "^24.9.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.1.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-import-resolver-typescript": "^2.0.0",
    "eslint-plugin-import": "^2.21.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-react": "^7.20.0",
    "eslint-plugin-react-hooks": "^2.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "prettier": "^2.0.5",
    "react-test-renderer": "16.11.0",
    "typescript": "^3.8.3"
  },

```

**Comment by leandrosouzaa** [comment] 2020-06-21 21:46
if you are using react-navigation v5, you need to check the branch on the v5 version.

https://github.com/IjzerenHein/react-navigation-shared-element/tree/navigation-v5

**Comment by moddatherrashed** [comment] 2020-09-17 12:58
@Zurdge did you clean the project or it did just work, because i tried to clean the project but the issue still persist

**Comment by ghoudi01** [comment] 2020-09-18 19:45
is there any solution yet

**Comment by moddatherrashed** [comment] 2020-09-19 15:12
@ghoudi01 can you show me your package.json?

**Comment by ghoudi01** [comment] 2020-09-19 22:42
@moddatherrashed `{
  "name": "placev2",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.12.0",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.9.6",
    "@react-native-community/slider": "^3.0.3",
    "@react-native-community/viewpager": "^4.1.6",
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/drawer": "^5.9.0",
    "@react-navigation/native": "^5.0.9",
    "@react-navigation/stack": "^5.1.1",
    "apisauce": "^1.1.2",
    "buffer": "^5.6.0",
    "expo": "~38.0.9",
    "expo-splash-screen": "^0.5.0",
    "expo-status-bar": "^1.0.0",
    "expo-updates": "~0.2.10",
    "immutable": "^4.0.0-rc.12",
    "lodash": "^4.17.20",
    "moment": "^2.27.0",
    "native-base": "^2.13.14",
    "parse": "^2.15.0",
    "pusher-js": "^7.0.0",
    "react": "16.13.1",
    "react-addons-update": "^15.6.2",
    "react-dom": "~16.11.0",
    "react-native": "0.63.2",
    "react-native-audio": "^4.3.0",
    "react-native-device-info": "^6.0.2",
    "react-native-document-picker": "^3.5.4",
    "react-native-easy-chat-ui": "^0.4.10",
    "react-native-emoji-selector": "^0.1.9",
    "react-native-fast-image": "^8.3.2",
    "react-native-flexi-radio-button": "^0.2.2",
    "react-native-fs": "^2.16.6",
    "react-native-geocoder": "^0.5.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-image-crop-picker": "^0.34.1",
    "react-native-image-picker": "^2.3.3",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.2",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-maps": "0.27.1",
    "react-native-masked-text": "^1.13.0",
    "react-native-modal": "^11.5.6",
    "react-native-popup-menu": "^0.15.9",
    "react-native-progress": "^4.1.2",
    "react-native-reanimated": "^1.9.0",
    "react-native-router-flux": "^4.2.0",
    "react-native-safe-area-context": "^3.1.7",
    "react-native-screens": "^2.11.0",
    "react-native-shared-element": "^0.7.0",
    "react-native-slider": "^0.11.0",
    "react-native-snackbar": "^2.2.3",
    "react-native-sound": "^0.11.0",
    "react-native-sound-player": "^0.10.4",
    "react-native-splash-screen": "^3.2.0",
    "react-native-status-bar-height": "^2.5.0",
    "react-native-typing-animation": "^0.1.7",
    "react-native-unimodules": "~0.10.1",
    "react-native-uuid": "^1.4.9",
    "react-native-vector-icons": "^7.0.0",
    "react-native-video": "^5.1.0-alpha8",
    "react-native-web": "~0.11.7",
    "react-native-webview": "^10.8.3",
    "react-navigation-shared-element": "^3.0.0",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-persist-transform-filter": "0.0.20",
    "redux-persist-transform-immutable": "^5.0.0",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

**Comment by tomasvarga** [comment] 2020-09-22 19:10
As pointed in different issue: https://github.com/IjzerenHein/react-navigation-shared-element/issues/79#issuecomment-694378660 install `react-navigation` `react-navigation-stack` as devDependencies and it should be working alright. 

`npm i react-navigation react-navigation-stack --save-dev `

**Comment by Keanottesen** [comment] 2020-09-23 14:43
Anyone found a solution to this yet?

**Comment by ghoudi01** [comment] 2020-09-24 10:00
@Keanottesen please ensure that you have this dependencies with version equal or above
```
"react-navigation-shared-element": "^3.0.0",
"@react-navigation/native": "^5.0.9",
"@react-navigation/stack": "^5.1.1",
```

**Comment by eveningkid** [comment] 2020-12-11 23:06
> if you are using react-navigation v5, you need to check the branch on the v5 version.
> 
> https://github.com/IjzerenHein/react-navigation-shared-element/tree/navigation-v5

Just adding up to this, turned out I was using `@prerelease` as stated in the documentation but `@next` was the one to use:

```
npm install react-navigation-shared-element@next
```

**Comment by vismayainnow8** [comment] 2021-06-10 07:03
> > if you are using react-navigation v5, you need to check the branch on the v5 version.
> > https://github.com/IjzerenHein/react-navigation-shared-element/tree/navigation-v5
> 
> Just adding up to this, turned out I was using `@prerelease` as stated in the documentation but `@next` was the one to use:
> 
> ```
> npm install react-navigation-shared-element@next
> ```

i tried this.. but didn't work

**Comment by IjzerenHein** [comment] 2021-08-24 10:05
I believe this was related to the early v3.0.0 prerelease version. Please upgrade to the latest version, which contains official support for React Navigation 5 and 6 (and 4 as well)
https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v3.1.2

**Comment by IjzerenHein** [comment] 2021-08-24 10:05
Closing this issue. Feel free to reopen with a test-case in the `example` that reproduces the problem

**Closed by IjzerenHein** 2021-08-24 10:05 UTC
