### ISSUE TITLE
[v5] Nested navigators (Tab Navigation) breaks navigation

### ISSUE THREAD

**Issue by DaveClissold** [IjzerenHein/react-navigation-shared-element#65] opened 2020-04-19 00:08 UTC
Firstly, great library and thanks for the work. 

Trying out the 0.7.0-alpha0 with React-Navigation 5, nested navigators, is in a Tab-Navigator breaks navigation completely within the stack.  have included a video below.  When I do not nest the navigator within the tab navigator and just use a stack navigator, the animations work fine and the navigation.navigate fires as expected.  When nested within a Tab, it just causes a re-render of the component in which the function is called. This problem persists in both android and ios

[https://drive.google.com/open?id=1MoMhtNSYOjq0yDNC-QvjQQ4Q-6TSPlfF](https://drive.google.com/open?id=1MoMhtNSYOjq0yDNC-QvjQQ4Q-6TSPlfF)

Here is the stack and tab navigators I'm using in the video.
```
const SearchStack= () => {
 const { Navigator, Screen } = createSharedElementStackNavigator<SearchParamsList>();
 return (
  <Navigator
   initialRouteName="search"
   headerMode="none"
   mode="modal"
   screenOptions={{
    cardStyleInterpolator: ({ current: { progress } }) => {
     const opacity = progress.interpolate({
      inputRange: [0, 1],
      outputRange: [0, 1],
      extrapolate: 'clamp',
     });
     return { cardStyle: { opacity, backgroundColor: 'white' } };
    },
   }}
  >
   <Screen
    name="search"
    component={FetchProducts}
    initialParams={{ listType: 'search' }}
   />
   <Screen
    name="product"
    component={Product}
    sharedElementsConfig={(route, otherRoute, showing) => {
     if (typeof route.params !== 'undefined') {
      const { product } = route.params;
      return [`image.${product._id}`, `background.${product._id}`];
     }
     return [];
    }}
   />
   <Screen name="ProductShops" component={ShopMap} />
   <Screen name="ProductSimilar" component={FetchSimilar} />
  </Navigator>
 );
};

const AppRoutes = () => {
 const Tab = createBottomTabNavigator<TabParamsList>();
 return (
  <Tab.Navigator
   initialRouteName="Search"
   tabBar={(props) => <BottomNavigation {...props} />}
  >
   <Tab.Screen
    name="Search"
    component={SearchStack}
    initialParams={{ listType: 'search' }}
   />
   {/* <Tab.Screen
    name='Suggestions'
    component={Search}
    initialParams={{ listType: 'search' }}
   />
   <Tab.Screen
    name='Tastings'
    component={Search}
    initialParams={{ listType: 'search' }}
   /> */}
   <Tab.Screen name="NewTasting" component={NewTastingStack} />
  </Tab.Navigator>
 );
};
```

**Comment by Acidfabric** [comment] 2020-04-19 18:39
I have the same problem

**Comment by IronTony** [comment] 2020-05-02 08:41
Yes, same here.

**Comment by IjzerenHein** [comment] 2020-05-07 19:32
Hi! i think the problem here stems from the fact that every time that `<SearchStack>` is rendered, it creates a new shared-element navigator. 

Try creating it once like this:

```js
const SearchStack = createSharedElementStackNavigator<SearchParamsList>();
const SearchStackScreen = () => (
  <SearchStack.Navigator>
    <SearchStack.Screen />
    <SearchStack.Screen />
  </SearchStack.Navigator>
);
```

**Comment by IronTony** [comment] 2020-05-07 19:36
I did as you suggested but without success. I will upload my small PoC if you want to check

**Comment by IjzerenHein** [comment] 2020-05-07 20:23
I've updated the example app and added a test-case framework to it. Could you add a test-case for this to the `./example` app? That would greatly help me find the problem.

**Comment by IronTony** [comment] 2020-05-07 20:45
I'll try. Thx

**Comment by IronTony** [comment] 2020-05-09 06:38
@IjzerenHein I tried but without success. This is a link to a simple app with Tabbar and a nested navigation where I found the problem. Maybe I didn't understand well something. 
If you could check and help would be awesome, and this can help you to find the bug (if it is a bug): https://we.tl/t-2pi6MvhC0d

Thank you in advance

**Comment by IjzerenHein** [comment] 2020-05-09 09:50
So you're saying that you tried adding it to the example app, but you couldn't reproduce the problem there?

**Comment by IronTony** [comment] 2020-05-09 17:58
Finally I have successfully extracted the last example you made with Tabbar and it seems working in a blank app. Now I will try apply to my case, in the app I attached in my last comment. Keep you update

**Comment by IronTony** [comment] 2020-05-11 05:53
@IjzerenHein Unfortunately I cannot reproduce the successfully try in the above PoC that I linked above.

**Comment by IronTony** [comment] 2020-05-11 05:56
For me is working everywhere using the test provided @IjzerenHein 
Thank you!!

**Comment by kubilaysalih** [comment] 2020-05-16 08:20
@IronTony Can you please share example nested code?

**Comment by IronTony** [comment] 2020-05-17 07:17
@kubilaysalih Here is the [repo](https://github.com/IronTony/react-native-navigation-5-shared-elements)

**Comment by willroyMyles** [comment] 2020-07-11 18:01
im not sure where the problem stems from but i worked around this by creating a viewpager and a tabbar for my tab navigator.
in the navigation docs, they demonstare how to deal with nested navigators... myabe the solution is there?

**Comment by interhub** [comment] 2021-03-01 11:52
SOLVING THIS PROBLEM FROM COMMENT  @IronTony :
In to Tab screen component add this:
```ts
import {createSharedElementStackNavigator} from 'react-navigation-shared-element'
export const Stack = createSharedElementStackNavigator()

const OrderTab=()=>{...}

export default () => {
    return <Stack.Navigator>
        <Stack.Screen name={'root'} component={OrderTab}/>
    </Stack.Navigator>
}
```
 instead : 
```ts
const OrderTab=()=>{...}
export default OrderTab
```

**Comment by p-syche** [comment] 2022-08-09 14:24
@DaveClissold thank you for opening this issue. It seems to be resolved with the help of @IjzerenHein and @IronTony so I'll close it.

@IronTony since you have a repo with an example app maybe you'd like to create a PR to add your example app as an example to this repo?

**Closed by p-syche** 2022-08-09 14:24 UTC
Labels: bug, navigation-5, tabs
