### ISSUE TITLE
sharedElements not running 

### ISSUE THREAD

**Issue by PepeValenzuela98** [IjzerenHein/react-navigation-shared-element#153] opened 2021-03-27 02:54 UTC
When i navigate or back to another screen can't see any animation or rezising transition, im using the same component to move around my screens changing some information. I tried to print a hello with console.log inside of sharedElements static method but its not printing

_Auth.js_
```javascript
import React from 'react';
import {StyleSheet, View, ScrollView} from 'react-native';
import BackButton from './BackButton';
import Logo from './Logo';
import {colors} from '../styles';
import {SharedElement} from 'react-navigation-shared-element';
import Social from './Social';
import HeaderText from './HeaderText';

const Auth = ({ headerText, rootScreen, showSocial, children}) => {
  return (
    <ScrollView style={{height: '100%', backgroundColor: colors.gray1}}>
      <SharedElement
        id="blueBackground"
        style={{
          ...styles.blueBackground,
          height: headerText ? '65%' : '50%',
        }}
      />

      <SharedElement
        id="header"
        style={{
          ...styles.header,
          marginTop: headerText ? 5 : 40,
        }}>
        {!rootScreen && <BackButton />}
        <Logo big={headerText ? false : true} />
      </SharedElement>

      <SharedElement id="headerText" style={{elevation: 11}}>
        {headerText && <HeaderText headerText={headerText} />}
      </SharedElement>

      <SharedElement id="content" style={styles.contentContainer}>
        <View style={styles.content}>{children}</View>
      </SharedElement>

      <SharedElement id="social" style={{elevation: 11}}>
        {showSocial && <Social />}
      </SharedElement>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  blueBackground: {
    backgroundColor: colors.blue2,
    borderWidth: 1,
    borderColor: colors.blue2,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    elevation: 10,
    position: 'absolute',
    width: '100%',
    height: '50%',
  },
  header: {
    elevation: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  contentContainer: {
    elevation: 11,
    marginTop: 35,
    alignItems: 'center',
  },
  content: {
    backgroundColor: '#fff',
    paddingVertical: 30,
    paddingHorizontal: 15,
    width: '80%',
    borderRadius: 10,
  },
});

Auth.sharedElements = (navigation, otherNavigation, showing) => {
  console.log("hello");
  return [
    {id: 'blueBackground', resize: 'stretch'},
    {id: 'header', resize: 'stretch'},
    {id: 'headerText', resize: 'clip'},
    {id: 'content', animation: 'fade-in'},
    {id: 'social', animation: 'move'},
  ];
};

export default Auth;
```

_AuthStack.js_
```javascript
import React from 'react';
import Welcome from '../screens/auth/Welcome';
import Login from '../screens/auth/Login';
import RecoveryPass from '../screens/auth/RecoveryPass';
import SignIn from '../screens/auth/SignIn';
import {createSharedElementStackNavigator} from 'react-navigation-shared-element';

const Stack = createSharedElementStackNavigator();

const RecoveryPassStep1 = () => <RecoveryPass step={1} />;
const RecoveryPassStep2 = () => <RecoveryPass step={2} />;
const RecoveryPassStep3 = () => <RecoveryPass step={3} />;
const RecoveryPassStep4 = () => <RecoveryPass step={4} />;

const AuthStack = () => {
  return (
    <Stack.Navigator headerMode="none" screenOptions={options}>
      <Stack.Screen name="Welcome" component={Welcome} />
      <Stack.Screen name="Login" component={Login} />
      <Stack.Screen name="RecoveryPass1" component={RecoveryPassStep1} />
      <Stack.Screen name="RecoveryPass2" component={RecoveryPassStep2} />
      <Stack.Screen name="RecoveryPass3" component={RecoveryPassStep3} />
      <Stack.Screen name="RecoveryPass4" component={RecoveryPassStep4} />
      <Stack.Screen name="SignIn" component={SignIn} />
    </Stack.Navigator>
  );
};

const options = () => ({
  gestureEnabled: false,
  transitionSpec: {
    open: {animation: 'timing', config: {duration: 1000}},
    close: {animation: 'timing', config: {duration: 1000}},
  },
  cardStyleInterpolator: ({current: {progress}}) => ({
    cardStyle: {opacity: progress},
  }),
});
export default AuthStack;

```

**Comment by IjzerenHein** [comment] 2021-08-24 11:07
Hi! Not sure what's going on here. It might be related to the prerelease version for React Navigation 5 that you are using. Please upgrade to the latest version which officially supports React Navigation 5 and 6:
https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v3.1.2

**Comment by IjzerenHein** [comment] 2021-08-24 11:09
Furthermore, I'm unable to reproduce this using any of the test-cases in the `example` app. Please add a test-case to the `example` app that reproduces this problem. Otherwise it will be very difficult to fix. Closing this for now, but feel free to re-open with additional info/repro case if this is still a problem.

**Closed by IjzerenHein** 2021-08-24 11:09 UTC
