### ISSUE TITLE
[v5] ANDROID transition not triggered when using the default goBack button in stack navigator

### ISSUE THREAD

**Issue by danielzzz** [IjzerenHein/react-navigation-shared-element#114] opened 2020-11-02 20:13 UTC
hi, 

it seems that the shared element work well forwards and backwards when using the back button, but it's not triggered when using the stock header back button.

thanks, cheers, dan

**Comment by razvanbretoiu** [comment] 2020-11-13 12:13
@danielzzz did you solve it? I'm facing the same issue on Android

**Comment by danielzzz** [comment] 2020-11-13 12:34
not sure, I think I just left it as it was, waiting for any news here

**Comment by MatheusPires99** [comment] 2020-12-03 00:37
I am facing this problem on iOS.

**Comment by jzxchiang1** [comment] 2021-07-02 17:00
Any update on this? Facing the same issue.

**Comment by hikhtiartaJNE** [comment] 2021-08-05 13:20
Set gestureEnabled to false, its solved for me

**Comment by IjzerenHein** [comment] 2021-08-24 10:27
Hi! I believe this was a problem with the early 3.0.0 prerelease version. Please upgrade to the latest version, which supports React Navigation 5 and 6 officially.
https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v3.1.2

**Comment by IjzerenHein** [comment] 2021-08-24 10:28
The `example` app contains many test-cases and I am unable to reproduce this problem with the latest version. I'm going to close this issue thereof. Feel free to reopen with a test-case in the `example` app in case this is still a problem.

**Closed by IjzerenHein** 2021-08-24 10:28 UTC
