### ISSUE TITLE
[V5] Transition happens only once?

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [IjzerenHein/react-navigation-shared-element#77] opened 2020-05-28 07:27 UTC
Thank  you for the great library. I bumped into an issue where the transition happens only once (had to refresh the app to see it once again).

```jsx
export const BlogItem = ({item, onPress}: Props) => {
  return (
    <CustomPressable onPress={onPress} style={styles.container}>
      <SharedElement id={`${item.id}.photo`}>
        <Image
          resizeMode="cover"
          style={styles.img}
          source={{uri: item.jetpack_featured_media_url}}
        />
      </SharedElement>
      <View style={styles.meta}>
        <Text style={styles.postTitle}>{escapeHtml(item.title.rendered)}</Text>
      </View>
    </CustomPressable>
  );
};
```

In the Detail screen:

```jsx
export const BlogPostDetail = ({navigation, route}: Props) => {
  console.log(route.params.id);
  return (
    <ScrollView>
      <SharedElement id={`${route.params.id}.photo`}>
        <Image
          resizeMode="cover"
          style={styles.image}
          source={{uri: route.params.jetpack_featured_media_url}}
        />
      </SharedElement>
      <Text onPress={() => navigation.goBack()}>Test</Text>
    </ScrollView>
  );
};
```

In the Navigator file:

```jsx
        <Stack.Screen
          name="BlogPostDetail"
          options={() => ({
            headerShown: false,
          })}
          sharedElementsConfig={(route) => {
            const {id} = route.params;
            return [{id: `${id}.photo`, otherId: `${id}.photo`}];
          }}
          component={BlogPostDetail}
        />
```

Result: https://streamable.com/hys2tu

In the first screen, list of items is contained in a TabNavigator, could it be... ?

**Comment by jp928** [comment] 2020-06-13 22:36
I am facing same issue. any work around?

**Comment by jp928** [comment] 2020-06-13 22:38
Also, does anybody know how to make a reverse transition?

**Comment by moalhaddar** [comment] 2020-06-27 01:03
I'm facing the same issue but with a drawer navigator nested inside a stack navigator.

My Top Stack Navigator
```
const StackNavigator = () => {

	return (
		<Stack.Navigator>
			<Stack.Screen
				name="DrawerNavigator"
				component={DrawerNavigator}
				options={{ headerShown: false }}
			/>
			<Stack.Screen
				name="profileImageScreen"
				component={ProfileImageScreen}
				sharedElements={(route, otherRoute, showing) => {
					return ["profileImage"];
				}}
			/>

		</Stack.Navigator>
	)
}


```


The drawer navigator contains a screen with a shared element. When navigating to the profileImageScreen in the top level stack navigator, the animation occurs only once going forward, pressing the back button doesn't make the animation work. It wont work any more unless you do a reload.

**Comment by linzera** [comment] 2020-06-29 16:48
I think this happens because the `header` from navigation is not being rendered (`headerShown`). Having the same issue on v4.

**Comment by webraptor** [comment] 2020-07-02 07:06
Also experiencing same issue with V5. Tried with `headerMode={'none'}` and default option and same issue.

**Comment by pke** [comment] 2020-07-23 00:50
> Also, does anybody know how to make a reverse transition?

Good question. From the videos I saw it looked like this was working out of the box with back navigation. But it doesnt.

**Comment by amitassaraf** [comment] 2020-07-29 08:21
+1 Happens to me too, I have a shared component between bottom tabs and a stack navigation page when doing the transition from the first tab it works fine, and from another tab, it works the first time then no longer happens.

**Comment by amitassaraf** [comment] 2020-08-02 08:02
@IjzerenHein Any ideas? :) Would love to help figure out if I can

**Comment by jdstregz** [comment] 2020-09-07 20:13
Hi, I was having the same issues. I had a nested Tab Navigator within a Shared Element Stack Navigator. Unfortunately this was not setting the prevScene value properly, so the first transition would work, but once going back there was no reset of the prevScene back to its original state.

Anyways, my workaround was to wrap each of my individual screens that i wanted to Shared-Transition from with its own SharedTransition Stack navigator.

My main app nav - you can control the sharedElements values from the higher level shared element nav:
`
const MainAppNavigator = () => {
  const [notification, setNotification] = useState(null);

  useEffect(() => {
    registerForPushNotificationsAsync();
    NotificationSystem.addNotificationReceivedListener((noti) => {
      setNotification(noti);
    });
    NotificationSystem.addNotificationResponseReceivedListener((res) => {
      console.log(res);
      console.log(notification);
    });
  }, []);

  return (
    <MainStack.Navigator headerMode="none">
      <MainStack.Screen name="TabNav" component={TabNav} />
      <MainStack.Screen
        name="EditProfile"
        component={EditProfileScreen}
        sharedElements={(route) => {
          const { item } = route.params;
          return [
            {
              id: `item.${item.id}`,
              animation: 'fade',
            },
          ];
        }}
      />
    </MainStack.Navigator>
  );
};
`
Tab navigator:
`const TabNav = () => {
  return (
    <Tab.Navigator
      initialRouteName="Dashboard"
      activeColor={theme.main.palette.selected}
      shifting
    >
      <Tab.Screen
        name="Profile"
        component={ProfileNav}
        options={{
          tabBarColor: '#222222',
          // eslint-disable-next-line react/prop-types
          tabBarIcon: ({ color }) => (
            <MaterialCommunityIcons name="account" color={color} size={26} />
          ),
        }}
      />
    </Tab.Navigator>
  );
};`

Profile Nav - really just a dedicated shared element stack nav for this one screen 
`import React from 'react';
import { createSharedElementStackNavigator } from 'react-navigation-shared-element';
import ProfileScreen from '../profile/ProfileScreen';

const ProfileStack = createSharedElementStackNavigator();

const ProfileNav = () => {
  return (
    <ProfileStack.Navigator headerMode="none">
      <ProfileStack.Screen name="Profile" component={ProfileScreen} />
    </ProfileStack.Navigator>
  );
};

export default ProfileNav;
`

**Comment by jdstregz** [comment] 2020-09-08 03:19
#80

**Comment by KDKHD** [comment] 2020-10-16 17:34
@jdstregz this does not work for me. I used your exact code :(

**Comment by KDKHD** [comment] 2020-10-16 21:44
Posted a solution that worked for me in #91

**Comment by cenaHara** [comment] 2020-11-17 14:30
> Hi, I was having the same issues. I had a nested Tab Navigator within a Shared Element Stack Navigator. Unfortunately this was not setting the prevScene value properly, so the first transition would work, but once going back there was no reset of the prevScene back to its original state. So there is probably a fix that needs to be made to fix behavior with nested tab navs.
> 
> Anyways, my workaround was to wrap each of my individual screens that i wanted to Shared-Transition from with its own SharedTransition Stack navigator.
> 
> My main app nav - you can control the sharedElements values from the higher level shared element nav:
> 
> ```
> const MainAppNavigator = () => {
>   const [notification, setNotification] = useState(null);
> 
>   return (
>     <MainStack.Navigator headerMode="none">
>       <MainStack.Screen name="TabNav" component={TabNav} />
>       <MainStack.Screen
>         name="EditProfile"
>         component={EditProfileScreen}
>         sharedElements={(route) => {
>           const { item } = route.params;
>           return [
>             {
>               id: `item.${item.id}`,
>               animation: 'fade',
>             },
>           ];
>         }}
>       />
>     </MainStack.Navigator>
>   );
> };
> ```
> 
> Tab navigator:
> 
> ```
> const TabNav = () => {
>   return (
>     <Tab.Navigator
>       initialRouteName="Dashboard"
>       activeColor={theme.main.palette.selected}
>       shifting
>     >
>       <Tab.Screen
>         name="Profile"
>         component={ProfileNav}
>         options={{
>           tabBarColor: '#222222',
>           // eslint-disable-next-line react/prop-types
>           tabBarIcon: ({ color }) => (
>             <MaterialCommunityIcons name="account" color={color} size={26} />
>           ),
>         }}
>       />
>     </Tab.Navigator>
>   );
> };
> ```
> 
> Profile Nav - really just a dedicated shared element stack nav for this one screen
> 
> ```
> import React from 'react';
> import { createSharedElementStackNavigator } from 'react-navigation-shared-element';
> import ProfileScreen from '../profile/ProfileScreen';
> 
> const ProfileStack = createSharedElementStackNavigator();
> 
> const ProfileNav = () => {
>   return (
>     <ProfileStack.Navigator headerMode="none">
>       <ProfileStack.Screen name="Profile" component={ProfileScreen} />
>     </ProfileStack.Navigator>
>   );
> };
> 
> export default ProfileNav;
> ```

it work but when i click another tab very lag

**Comment by TheLonelyAstronaut** [comment] 2020-11-17 15:11
> > Hi, I was having the same issues. I had a nested Tab Navigator within a Shared Element Stack Navigator. Unfortunately this was not setting the prevScene value properly, so the first transition would work, but once going back there was no reset of the prevScene back to its original state. So there is probably a fix that needs to be made to fix behavior with nested tab navs.
> > Anyways, my workaround was to wrap each of my individual screens that i wanted to Shared-Transition from with its own SharedTransition Stack navigator.
> > My main app nav - you can control the sharedElements values from the higher level shared element nav:
> > ```
> > const MainAppNavigator = () => {
> >   const [notification, setNotification] = useState(null);
> > 
> >   return (
> >     <MainStack.Navigator headerMode="none">
> >       <MainStack.Screen name="TabNav" component={TabNav} />
> >       <MainStack.Screen
> >         name="EditProfile"
> >         component={EditProfileScreen}
> >         sharedElements={(route) => {
> >           const { item } = route.params;
> >           return [
> >             {
> >               id: `item.${item.id}`,
> >               animation: 'fade',
> >             },
> >           ];
> >         }}
> >       />
> >     </MainStack.Navigator>
> >   );
> > };
> > ```
> > 
> > 
> > Tab navigator:
> > ```
> > const TabNav = () => {
> >   return (
> >     <Tab.Navigator
> >       initialRouteName="Dashboard"
> >       activeColor={theme.main.palette.selected}
> >       shifting
> >     >
> >       <Tab.Screen
> >         name="Profile"
> >         component={ProfileNav}
> >         options={{
> >           tabBarColor: '#222222',
> >           // eslint-disable-next-line react/prop-types
> >           tabBarIcon: ({ color }) => (
> >             <MaterialCommunityIcons name="account" color={color} size={26} />
> >           ),
> >         }}
> >       />
> >     </Tab.Navigator>
> >   );
> > };
> > ```
> > 
> > 
> > Profile Nav - really just a dedicated shared element stack nav for this one screen
> > ```
> > import React from 'react';
> > import { createSharedElementStackNavigator } from 'react-navigation-shared-element';
> > import ProfileScreen from '../profile/ProfileScreen';
> > 
> > const ProfileStack = createSharedElementStackNavigator();
> > 
> > const ProfileNav = () => {
> >   return (
> >     <ProfileStack.Navigator headerMode="none">
> >       <ProfileStack.Screen name="Profile" component={ProfileScreen} />
> >     </ProfileStack.Navigator>
> >   );
> > };
> > 
> > export default ProfileNav;
> > ```
> 
> it work but when i click another tab very lag

All is fine for me, maybe you should use FlatList instead of ScrollView (just to increase render speed, if you have scrollable content in the screen)

**Comment by cenaHara** [comment] 2020-11-17 15:56
hi @TheLonelyAstronaut this is my config tab bottom 
https://pastebin.com/TmkitQAg
and when I click another tab, it was very laggy and jerky, even though my tab had nothing

**Comment by cenaHara** [comment] 2020-11-17 15:56
hi @TheLonelyAstronaut this is my config tab bottom 
[https://pastebin.com/TmkitQAg](https://pastebin.com/TmkitQAg)
and when I click another tab, it was very laggy and jerky, even though my tab had nothing

**Comment by TheLonelyAstronaut** [comment] 2020-11-17 18:34
> hi @TheLonelyAstronaut this is my config tab bottom
> https://pastebin.com/TmkitQAg
> and when I click another tab, it was very laggy and jerky, even though my tab had nothing

Try to remove listeners, idk

**Comment by llamaluvr** [comment] 2020-11-22 06:47
I had an issue where my transitions would keep working from the tab to the child screen until I navigated to another tab and back to the first. @jdstregz resolved this issue, but I do notice that, after I come back from another tab for the first time, my transitions are no longer smooth. The transition from parent tab to child screen is fine, but then after popping the child screen off the stack, the image in our shared view stutters on the way back to its original position. With the default iOS slide, it would actually briefly move far to the left of its original position for a moment. When I switched to a fade transition, it was less pronounced, but still visible- then it would kind of stutter vertically, appearing slightly higher before snapping back into place.

Just wondering if anyone else has noticed anything similar. Thanks!

**Comment by amitassaraf** [comment] 2020-11-26 11:50
@jdstregz @IjzerenHein 

My issue appears to be when navigating from a tab to a tab, then back, then navigating on the stack, the animation appears but as soon as I go back, it stops working for good. (Before navigations from any tabs the animation works back and forth without issues).

I have noticed that as soon as I go back after navigating between the tabs then through the stack, I get this warning in the console:

`Could not locate shadow view with tag #4469, this is probably caused by a temporary inconsistency between native views and shadow views.`

This is the point it breaks at.

I've tried every solution proposed.

**Comment by amitassaraf** [comment] 2020-11-26 14:49
FYI I managed to solve it on my end, instead of doing normal navigation between the tabs, I reset the navigation stack to that specific tab. This means the "state" of the tab isn't saved but its fine for me for now. Obviously, if this would have been solved through the library it would be better.

Added this on my BottomTabs.Screen:

```javascript

                    listeners={{
                        tabPress: e => {
                            e.preventDefault();
                            resetToTab(navigationRef.current, e.target.split('-')[0]);
                        },
                    }}

```

**Comment by Trashpants** [comment] 2020-12-09 22:06
So I've had this issue when pushing onto a stack - I want to be able to push a copy of the same screen onto the stack with different params.

When ONLY adding to the stack the transitions work perfectly, however the moment you try to pop off the stack it breaks the whole stack until the app is restarted.

What Ive noticed is that if you update the navigator screen to have:

```
      <Stack.Screen
        name="Detail"
        component={DetailScreen}
        sharedElements={(route, otherRoute, showing) => {
          console.log(
            `${
              showing
                ? `FORWARD: ${otherRoute.key} -> ${route.key}`
                : `BACK: ${route.key} -> ${otherRoute.key}`
            }`
          );
          const { details } = route.params;
          return [`image.${details.primaryImage}`];
        }}

... />
```

When going backwards and forwards between 2 screens that are totally unique they will alter the showing variable as needed:

```
FORWARD: DashboardRoot-wmsmcp5rDn9YBubuQbyFL -> Detail-bPRn5Jp0o5I2vSBAOHwWh
BACK: Detail-bPRn5Jp0o5I2vSBAOHwWh -> DashboardRoot-wmsmcp5rDn9YBubuQbyFL
FORWARD: DashboardRoot-wmsmcp5rDn9YBubuQbyFL -> Detail-2HKAP2aJBMXOvUDNS3Wy2
```

but when you start navigating using push it will utterly mess up - even navigating to itself, the below output doesn't show that I had a stack that had 2 PropertyDetail Screens that I came back out of - only the final back action was from a screen that used `navigation.navigate('SCREEN')` to get to in the first place.

```
FORWARD: DashboardRoot-wmsmcp5rDn9YBubuQbyFL -> PropertyDetail-jtmCyaJFSzuzukb6qlpXZ
FORWARD: DashboardRoot-NjpotmuUyziWj2QycvM3v -> PropertyDetail-l8IbqVs9PIkyxpnw2__w7
FORWARD: PropertyDetail-l8IbqVs9PIkyxpnw2__w7 -> PropertyDetail-l8IbqVs9PIkyxpnw2__w7 **TO ITSELF**
FORWARD: PropertyDetail-l8IbqVs9PIkyxpnw2__w7 -> PropertyDetail-TenbZP7dchmv6pHAK0-Ov
FORWARD: PropertyDetail-TenbZP7dchmv6pHAK0-Ov -> PropertyDetail-l8IbqVs9PIkyxpnw2__w7
FORWARD: PropertyDetail-TenbZP7dchmv6pHAK0-Ov -> PropertyDetail-TenbZP7dchmv6pHAK0-Ov
FORWARD: PropertyDetail-TenbZP7dchmv6pHAK0-Ov -> PropertyDetail-H0dDqLEenMDdpb0Yo4qhs
FORWARD: PropertyDetail-H0dDqLEenMDdpb0Yo4qhs -> PropertyDetail-l8IbqVs9PIkyxpnw2__w7
FORWARD: PropertyDetail-H0dDqLEenMDdpb0Yo4qhs -> PropertyDetail-TenbZP7dchmv6pHAK0-Ov
FORWARD: PropertyDetail-H0dDqLEenMDdpb0Yo4qhs -> PropertyDetail-H0dDqLEenMDdpb0Yo4qhs
FORWARD: PropertyDetail-H0dDqLEenMDdpb0Yo4qhs -> PropertyDetail-l8IbqVs9PIkyxpnw2__w7
FORWARD: PropertyDetail-H0dDqLEenMDdpb0Yo4qhs -> PropertyDetail-TenbZP7dchmv6pHAK0-Ov
BACK: PropertyDetail-TenbZP7dchmv6pHAK0-Ov -> DashboardRoot-NjpotmuUyziWj2QycvM3v

```

Anyone else see anything similar to this?

**Comment by baronha** [comment] 2021-01-07 09:17
I have the same error :( !

**Comment by tharun-slarn** [comment] 2021-02-19 14:15
creating a separate stack for source file inside tab worked for me

Eg:

const HomeStack = createSharedElementStackNavigator();
function HomeStackScreen() {
return (
<HomeStack.Navigator>
<HomeStack.Screen name="Source" component={Sourcescreen} />
</HomeStack.Navigator>
);
}

<Tab.Screen name="Home" component={HomeStackScreen}/>

**Comment by edtjulien** [comment] 2021-03-09 20:45
@amitassaraf The whole reinit of the "state" makes the trick not usable in my case. I have the same issue and your solution solve it but creates too much sides effects (anyway, that's better than nothing because at least, your solution works ;)
@tharun-slarn that's work too, great. But, in my case, I need to have my Stack Navigator out of the Tab Navigator because I don't want to have the bottom Tab Bar visible

I hope a fix can be fine in a next release

**Comment by IjzerenHein** [comment] 2021-08-24 10:00
I believe the original problem had to do with the default `TransitionIOSSpec` in React Navigation which used a spring and it took a too long time for it to settle. This affected the detection of the shared element transitions. This has been fixed in both React Navigation 4 and 5/6 a while back.
https://github.com/react-navigation/react-navigation/pull/8028

As this issue (and other reported issues) is quite old, strongly I recommend updating to the latest released version. It contains official support for React Navigation 5 and contains a bunch of bug fixes.
https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v3.1.2

**Comment by IjzerenHein** [comment] 2021-08-24 10:00
Closing this issue. Feel free to re-open with additional info and a test-case in the `example` app if this problem still occurs

**Closed by IjzerenHein** 2021-08-24 10:00 UTC
